### ISSUE TITLE
'GVGAI_Env' object has no attribute 'get_action_meanings'

### ISSUE THREAD

**Issue by kevinwu23** [rubenrtorrado/GVGAI_GYM#6]
Hi,

I am trying to call 'get_action_meanings' to run GVGAI games in an atari-like set-up, but it seems they are not included. Is this something I can easily recreate on my own?

Thanks!

**Comment by pbontrager** [comment]
I implemented it, you can pull an update. Remember that you need to "unwrap" the environment to access custom functions outside of gym. So env.unwrapped.get_action_meanings() works now.

**Comment by kevinwu23** [comment]
Thanks for the update!

I am still running into several issues getting the GVGAI environment to work as an Atari Env from
https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py

Here are a few examples: 
-- Assertion Error from "assert env.unwrapped.get_action_meanings()[0] == 'NOOP'"

-- 'GVGAI_Env' object has no attribute 'np_random'

-- 'GVGAI_Env' object has no attribute 'ale'

I have created some workarounds from these errors but I'm wondering if there is a more clean workaround.

Thanks again.

**Comment by pbontrager** [comment]
Ultimately the GVGAI environment is not an Atari environment and only complies with the general Gym interface. For example, GVGAI wouldn’t have an attribute ‘ale’ which stands for Atari Learning Environment. Also the action meanings are provided by the GVGAI environment and are consistent with this environment instead of Atari. If you want certain features of the Atari environment wrapper, I’d recommend making your own copy of the wrapper and only keeping the code that applies to GVGAI.
