### ISSUE TITLE
Incorrect "observation_space" property for games with varying level shapes

### ISSUE THREAD

**Issue by ercumentilhan** [rubenrtorrado/GVGAI_GYM#8]
Hello,

`observation_space` property of an environment seems to be set to match **lvl0** of the environment, which is incorrect if it has levels with different shapes than **lvl0**.

Here is the code block I used to observe this behavior:
```
env = gym.make('gvgai-testgame3-lvl1-v0')  # Actual level shape is (70, 310, 4)

print(env.observation_space)  # prints Box(70, 130, 4)

observation = env.reset()

print(env.observation_space)  # prints Box(70, 130, 4)
print(np.shape(observation))  # prints (70, 310, 4)
```

**Comment by pbontrager** [comment]
Hi,

Thank you for pointing this out. This was caused because the observation_space was being set before the level was. So like you suspected, observation_space was getting set to the size of lvl0. The gym interface doesn't allow this variable to be updated again after it's been set.

This has been corrected now and pushed to the main branch.
